### ISSUE TITLE
Error when using Attributes API

### ISSUE THREAD

**Issue by bingjyang** [rocketjob/symmetric-encryption#124]
### Environment

Provide at least:
* Ruby Version.
2.5.7p57
* Symmetric Encryption Version.
v4.3 (f5bd0cf2f42b787339170888387c7e62dfd565c3)
* Application/framework names and versions (e.g. Rails, Sinatra, Puma, etc.).
Rails 5.2.2.1
* Full Stack Trace, if an exception is being raised.
```
NoMethodError: private method `type' called for #<SymmetricEncryption::ActiveRecord::EncryptedAttribute:0x00007f8ab388bea0>
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_methods/time_zone_conversion.rb:86:in `create_time_zone_conversion_attribute?'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_methods/time_zone_conversion.rb:75:in `block (2 levels) in inherited'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_decorators.rb:85:in `block in matching'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_decorators.rb:84:in `select'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_decorators.rb:84:in `matching'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_decorators.rb:80:in `decorators_for'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_decorators.rb:71:in `apply'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_decorators.rb:53:in `block in load_schema!'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_decorators.rb:52:in `each'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_decorators.rb:52:in `load_schema!'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/model_schema.rb:459:in `block in load_schema'
/Users/bing/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/model_schema.rb:456:in `load_schema'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/model_schema.rb:382:in `_default_attributes'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/model_schema.rb:329:in `attributes_builder'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/persistence.rb:70:in `instantiate'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/querying.rb:53:in `block (2 levels) in find_by_sql'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/result.rb:57:in `block in each'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/result.rb:57:in `each'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/result.rb:57:in `each'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/querying.rb:53:in `map'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/querying.rb:53:in `block in find_by_sql'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/querying.rb:52:in `find_by_sql'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation.rb:560:in `block in exec_queries'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation.rb:547:in `exec_queries'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation.rb:422:in `load'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation.rb:200:in `records'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation.rb:195:in `to_ary'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation/finder_methods.rb:528:in `find_nth_with_limit'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation/finder_methods.rb:513:in `find_nth'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation/finder_methods.rb:125:in `first'
/Users/bing/dev/fireball/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/querying.rb:5:in `first'
```

Error is happening here: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb#L86

Seems the attr_reader :type in `SymmetricEncryption::ActiveRecord::EncryptedAttribute` should be public.

I can provide more info if necessary, but it seems like a straightforward issue.

### Expected Behavior

* Describe your expectation of how Symmetric Encryption should behave.
* Ideally, provide a standalone Ruby script or a link to an example repository that helps reproduce the issue.

### Actual Behavior

* Describe or show the actual behavior.
* Provide text or screen capture showing the behavior.

### Pull Request

* Consider submitting a Pull Request with a fix for the issue.
* Or, even a Pull request that only includes a test that reproduces the problem.

**Comment by reidmorrison** [comment]
It looks like `type` is reserved by Active Model, so I renamed the Symmetric Encryption `type`. 

We may also want to consider using the Active Model type coercion routines instead of the coercion built into Symmetric Encryption. As we use this new approach it should give more clarity on the type conversion.

Will published gem 4.3.1 shortly with the renamed `type` to prevent overriding the Active Model one.
