### ISSUE TITLE
Deprecation warning regarding Module#parent when used with Rails 6.0.0

### ISSUE THREAD

**Issue by jasonl** [rocketjob/symmetric-encryption#136]
### Environment
Ruby: 2.6.0
Rails: 6.0.0
symmetric_encryption: 4.3.0

### Expected Behavior
No deprecation warning.

### Actual Behavior
When booting a Rails 6.0.0 app which has symmetric_encryption in the `Gemfile`, the following warning is shown:
```
DEPRECATION WARNING: `Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1. (called from <module:Core> at /<deleted>/config/application.rb:23)
```
Running Rails with `ActiveSupport::Deprecation.debug = true` in `application.rb` gives a full stacktrace:
```
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/railtie.rb:32:in `block in <class:Railtie>'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/application.rb:96:in `inherited'
<additional irrelevant lines deleted>
```

**Comment by reidmorrison** [comment]
Fixed in https://github.com/rocketjob/symmetric-encryption/pull/134
