### ISSUE TITLE
GCP kms not working it latest gems

### ISSUE THREAD

**Issue by rcalosso** [rocketjob/symmetric-encryption#150]
### Environment

Provide at least:
* Ruby Version.
* 2.7.2
* Symmetric Encryption Version.
* 4.3.0
* Application/framework names and versions (e.g. Rails, Sinatra, Puma, etc.).
* Rails
* Full Stack Trace, if an exception is being raised.
* bundle exec symmetric-encryption --generate --keystore gcp --app-name Sample --environments "production"
bundler: failed to load command: symmetric-encryption (/opt/narvar/vendor/bundle/ruby/2.7.0/bin/symmetric-encryption)
NameError: uninitialized constant Google::Cloud::Kms::V1::KeyManagementServiceClient
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/keystore/gcp.rb:67:in `client'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/keystore/gcp.rb:59:in `encrypt'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/keystore/gcp.rb:45:in `write'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/keystore/gcp.rb:18:in `generate_data_key'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/keystore.rb:24:in `block in generate_data_keys'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/keystore.rb:18:in `each'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/keystore.rb:18:in `generate_data_keys'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/cli.rb:222:in `generate_new_config'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/cli.rb:66:in `run!'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/lib/symmetric_encryption/cli.rb:14:in `run!'
  /opt/narvar/vendor/bundle/ruby/2.7.0/gems/symmetric-encryption-4.3.0/bin/symmetric-encryption:5:in `<top (required)>'
  /opt/narvar/vendor/bundle/ruby/2.7.0/bin/symmetric-encryption:23:in `load'
  /opt/narvar/vendor/bundle/ruby/2.7.0/bin/symmetric-encryption:23:in `<top (required)>'
### Expected Behavior

Expect to generate config file

### Actual Behavior

Stack trace, crash cause module / class name is wrong

### Pull Request

Will work on PR, but looks like line 67 above is missing ::, should read

self.class::KMS::KeyManagementService::Client.new(timeout: 2, credentials: credentials)

**Comment by reidmorrison** [comment]
If Google have changed their API, when you submit the PR, please verify that the new changes are backward compatible with the previous Google API version.

**Comment by reidmorrison** [comment]
Fixed in the upcoming v5.0.0 release.

The GCP keystore has been ported to `google-cloud-kms` v2. The client is now built as `Google::Cloud::Kms::V1::KeyManagementService::Client`, so the `NameError` is gone. The port went a little further than the constant rename:

* `encrypt` and `decrypt` now pass keyword arguments.
* The crypto key name is built from the `Paths` module, so it is available before credentials are needed. The generated name is unchanged (`projects/{project}/locations/{location}/keyRings/{app}/cryptoKeys/{env}`), so existing configurations still resolve to the same key.
* `Keystore::Gcp.generate_data_key` now accepts a `dek:` argument. Key rotation previously raised `ArgumentError` for this keystore.

On backward compatibility: the old `KeyManagementServiceClient` constant no longer exists in the current gem, so v5 requires `google-cloud-kms` v2. That is noted as a breaking change in the CHANGELOG.

The reason this went unnoticed for so long is that the only GCP coverage skipped without `GOOGLE_CLOUD_KEYFILE` set. v5 adds a stubbed test file that exercises the keystore with no credentials and no network calls, so a regression like this fails the suite now.
