### ISSUE TITLE
FactoryGirl with SymmetricEncryption

### ISSUE THREAD

**Issue by gciampa** [rocketjob/symmetric-encryption#44]
I'm facing an issue when trying to run my tests which are using FactoryGirl. Below I've pasted my factory and relevant bits of stack trace that I'm getting back. I'm relatively new to FactoryGirl, so I'm not sure if there is an alternative strategy I should be using along with SymmetricEncryption. I have been able to validate that data is being encrypted via the console when I create a new instance. Any help would be appreciated!

``` Ruby
FactoryGirl.define do
  factory :answer do |answer|
    sequence(:answer)      { |i| "Answer Text #{i}" }
    association :sender, factory: :user
    assigned_question
  end
end
```

```
3) Answer should not be valid
     Failure/Error: answer = build(:answer, assigned_question: assigned_question)
     NoMethodError:
       undefined method `encrypted_answer=' for #<Answer:0x007fbb0b37ef10>
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/activemodel-3.2.19/lib/active_model/attribute_methods.rb:407:in `method_missing'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/activerecord-3.2.19/lib/active_record/attribute_methods.rb:149:in `method_missing'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/symmetric-encryption-3.6.0/lib/symmetric_encryption/generator.rb:36:in `answer='
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/evaluation.rb:12:in `object'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/strategy/build.rb:9:in `result'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/factory.rb:42:in `run'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # /Users/gregciampa/.gem/ruby/1.9.3/gems/factory_girl-4.1.0/lib/factory_girl/strategy_syntax_method_registrar.rb:19:in `block in define_singular_strategy_method'
     # ./spec/models/answer_spec.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by ACPK** [comment]
@gciampa What was the fix as I'm hitting a similar error?
