### ISSUE TITLE
Generate files command appears to suggest wrong parameter for app name

### ISSUE THREAD

**Issue by jeremylang** [rocketjob/symmetric-encryption#90]
Suggested command to generate config/key files appears to suggest the wrong parameter for app name.

```
To generate a new config file and key files: symmetric-encryption --generate --key-path /etc/example_app --app_name example_app
```

```
/usr/local/bundle/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/cli.rb:33:in `initialize': invalid option: --app_name (OptionParser::InvalidOption)
	from /usr/local/bundle/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/cli.rb:14:in `new'
	from /usr/local/bundle/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/cli.rb:14:in `run!'
	from /usr/local/bundle/gems/symmetric-encryption-4.0.0/bin/symmetric-encryption:5:in `<top (required)>'
	from /usr/local/bundle/bin/symmetric-encryption:17:in `load'
	from /usr/local/bundle/bin/symmetric-encryption:17:in `<main>'
```

Using `--app-name` works.

**Comment by reidmorrison** [comment]
Thank you for letting me know. It should display the correct message now.
