### ISSUE TITLE
Unable to use --rotate-keys generated from v3.8.3 in v4.0.0

### ISSUE THREAD

**Issue by mikepjb** [rocketjob/symmetric-encryption#95]
I am unable to execute `symmetric-enryption --rotate-keys` in a project I'm currently working on, below is the output. Creating a new repository I am able to generate and then rotate those keys (only when using sudo).

This is happening under ruby 2.5.0 using Arch Linux, let me know if there's anymore information that might be helpful.

```
$ symmetric-encryption --rotate-keys
Traceback (most recent call last):
        10: from /home/mikepjb/.gem/ruby/2.5.0/bin/symmetric-encryption:23:in `<main>'
         9: from /home/mikepjb/.gem/ruby/2.5.0/bin/symmetric-encryption:23:in `load'
         8: from /home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/bin/symmetric-encryption:5:in `<top (required)>'
         7: from /home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/cli.rb:14:in `run!'
         6: from /home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/cli.rb:62:in `run!'
         5: from /home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/cli.rb:233:in `run_rotate_keys'
         4: from /home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/keystore.rb:33:in `rotate_keys!'
         3: from /home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/keystore.rb:33:in `each_pair'
         2: from /home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/keystore.rb:53:in `block in rotate_keys!'
         1: from /home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/keystore/memory.rb:20:in `new_key_config'
/home/mikepjb/.gem/ruby/2.5.0/gems/symmetric-encryption-4.0.0/lib/symmetric_encryption/keystore/memory.rb:48:in `write': undefined method `encrypted_key=' for #<SymmetricEncryption::Keystore::Memory:0x00005624cbc6a5e8> (NoMethodError)
Did you mean?  encrypted_key
```

**Comment by reidmorrison** [comment]
If Symmetric Encryption was upgraded along the way, try running `symmetric-encryption --migrate` prior to rotating the keys.
